//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnBoardService.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveData
    {
        public int Id { get; set; }
        public double Lat { get; set; }
        public double Lon { get; set; }
        public string StatusCode { get; set; }
    
        public virtual User User { get; set; }
    }
}
