//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnBoardService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OnBoardResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OnBoardResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnBoardService.OnBoardResource", typeof(OnBoardResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=&quot;|DataDirectory|\Database\CoreDatabase.mdf&quot;;Integrated Security=True.
        /// </summary>
        internal static string LocalDatabaseConStr {
            get {
                return ResourceManager.GetString("LocalDatabaseConStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=e8yqwmqjxx.database.windows.net;Initial Catalog=fundata;Integrated Security=False;User ID=johnsonp;Password=Qwerty123.;Connect Timeout=60;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False.
        /// </summary>
        internal static string RemoteDatabaseConstr {
            get {
                return ResourceManager.GetString("RemoteDatabaseConstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select MAX(Id)From [dbo].[User].
        /// </summary>
        internal static string Sql_UserGetMaxUserId {
            get {
                return ResourceManager.GetString("Sql_UserGetMaxUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select * From [dbo].[User]
        ///Where Id={0}.
        /// </summary>
        internal static string Sql_UserGetUserById_Id {
            get {
                return ResourceManager.GetString("Sql_UserGetUserById_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select * From [dbo].[User]
        ///Where NickName = &apos;{0}&apos;;.
        /// </summary>
        internal static string Sql_UserGetUserByNickName_NickName {
            get {
                return ResourceManager.GetString("Sql_UserGetUserByNickName_NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[User] (Id,NickName,GroupId)
        ///Values (&apos;{0}&apos;,&apos;{1}&apos;,&apos;{2}&apos;);.
        /// </summary>
        internal static string Sql_UserInsertUser_Id_NickName_GroupId {
            get {
                return ResourceManager.GetString("Sql_UserInsertUser_Id_NickName_GroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [dbo].[User]
        ///SET NickName = &apos;{1}&apos;, GroupId=&apos;{2}&apos;
        ///WHERE Id=&apos;{0}&apos;;.
        /// </summary>
        internal static string Sql_UserUpdateUserById_Id_Nickname_GroupId {
            get {
                return ResourceManager.GetString("Sql_UserUpdateUserById_Id_Nickname_GroupId", resourceCulture);
            }
        }
    }
}
